#!/usr/bin/with-contenv bash

cd /app/musicbrainz || exit

# number of processes
NPROC=${NPROC:-5}

exec \
	s6-setuidgid abc plackup -I lib -s FCGI \
	-E deployment --port 55901 --nproc "$NPROC" \
	--pid fcgi.pid --keep-stderr=1 > /dev/null 2>&1

