#!/usr/bin/with-contenv bash

# create redis folders
mkdir -p /data/redis /var/log/redis

# configure redis
if [ ! -f "/config/redis.conf" ]; then
cp /etc/redis.conf /config/redis.conf
sed 's/^loglevel notice/loglevel warning/' -i /config/redis.conf
sed 's/^daemonize yes/daemonize no/' -i /config/redis.conf
sed 's/^bind 127.0.0.1/bind 0.0.0.0/' -i /config/redis.conf
sed 's/^logfile \/var\/log\/redis\/redis-server.log/logfile \"\"/' -i /config/redis.conf
sed -i 's#/var/lib/redis#/data/redis#g' /config/redis.conf
fi

# create final folders for slave log
mkdir -p /config/log

# set permissions
chown -R abc:abc /config  /data/redis /var/log/redis
